name: Deploy to website

on:
  push:
    branches: ["master"]
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

concurrency:
  group: deploy-to-website
  cancel-in-progress: false

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install SSH Key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

      - name: Refresh
        env:
          DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
          DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
          DATABASE_USER: ${{ secrets.DATABASE_USER }}
          DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          DATABASE_PORT: ${{ secrets.DATABASE_PORT }}
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -r src/python/requirements.txt
          python3 src/python/db_to_json.py

      - name: Deploy
        run: rsync -avz -e "ssh -o StrictHostKeyChecking=no" --delete ${{ github.workspace }}/src/www/ root@${{ secrets.DROPLET_IP }}:/var/www/html
