name: Format

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: "22"

      - name: Install formatters
        run: |
          npm install --global prettier
          pip install --user black

      - name: Check format
        run: |
          prettier --check "**/*.{css,html,js,json,md,yaml}"
          python3 -m black --check src/python