name: Typecheck

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install mypy
        run: pip install mypy

      - name: Install dependencies
        run: pip install -r src/python/requirements.txt

      - name: mypy check
        run: mypy --strict src/python
